
import pandas as pd

def custom():
    label = {'afsl_ad' : 'afsl_ad',
            'afsl_area of end region 1(mm^2)' : 'afsl_area_of_end_region_1',
            'afsl_area of end region 2(mm^2)' : 'afsl_area_of_end_region_2',
            'afsl_branch volume(mm^3)' : 'afsl_branch_volume',
            'afsl_curl' : 'afsl_curl',
            'afsl_diameter(mm)' : 'afsl_diameter',
            'afsl_dti_fa' : 'afsl_dti_fa',
            'afsl_elongation' : 'afsl_elongation',
            'afsl_irregularity' : 'afsl_irregularity',
            'afsl_irregularity of end region 1' : 'afsl_irregularity_of_end_region_1',
            'afsl_irregularity of end region 2' : 'afsl_irregularity_of_end_region_2',
            'afsl_iso' : 'afsl_iso',
            'afsl_md' : 'afsl_md',
            'afsl_mean length(mm)' : 'afsl_mean_length',
            'afsl_nrdi02L' : 'afsl_nrdi02L',
            'afsl_nrdi04L' : 'afsl_nrdi04L',
            'afsl_nrdi06L' : 'afsl_nrdi06L',
            'afsl_number of tracts' : 'afsl_number_of_tracts',
            'afsl_qa' : 'afsl_qa',
            'afsl_radius of end region 1(mm)' : 'afsl_radius_of_end_region_1',
            'afsl_radius of end region 2(mm)' : 'afsl_radius_of_end_region_2',
            'afsl_rd' : 'afsl_rd',
            'afsl_rdi': 'afsl_rdi',
            'afsl_span(mm)' : 'afsl_span',
            'afsl_total area of end regions(mm^2)' : 'afsl_total_area_of_end_regions',
            'afsl_total radius of end regions(mm)' : 'afsl_total_radius_of_end_regions',
            'afsl_total surface area(mm^2)' : 'afsl_total_surface_area',
            'afsl_trunk volume(mm^3)' : 'afsl_trunk_volume',
            'afsl_volume(mm^3)' : 'afsl_volume',
            'afsr_ad' : 'afsr_ad',
            'afsr_area of end region 1(mm^2)' : 'afsr_area_of_end_region_1',
            'afsr_area of end region 2(mm^2)' : 'afsr_area_of_end_region_2',
            'afsr_branch volume(mm^3)' : 'afsr_branch_volume',
            'afsr_curl' : 'afsr_curl',
            'afsr_diameter(mm)' : 'afsr_diameter',
            'afsr_dti_fa' : 'afsr_dti_fa',
            'afsr_elongation' : 'afsr_elongation',
            'afsr_irregularity' : 'afsr_irregularity',
            'afsr_irregularity of end region 1' : 'afsr_irregularity_of_end_region_1',
            'afsr_irregularity of end region 2' : 'afsr_irregularity_of_end_region_2',
            'afsr_iso' : 'afsr_iso',
            'afsr_md' : 'afsr_md',
            'afsr_mean length(mm)' : 'afsr_mean_length',
            'afsr_nrdi02L' : 'afsr_nrdi02L',
            'afsr_nrdi04L' : 'afsr_nrdi04L',
            'afsr_nrdi06L' : 'afsr_nrdi06L',
            'afsr_number of tracts' : 'afsr_number_of_tracts',
            'afsr_qa' : 'afsr_qa',
            'afsr_radius of end region 1(mm)' : 'afsr_radius_of_end_region_1',
            'afsr_radius of end region 2(mm)' : 'afsr_radius_of_end_region_2',
            'afsr_rd' : 'afsr_rd',
            'afsr_rdi' : 'afsr_rdi',
            'afsr_span(mm)' : 'afsr_span',
            'afsr_total area of end regions(mm^2)' : 'afsr_total_area_of_end_regions',
            'afsr_total radius of end regions(mm)' : 'afsr_total_radius_of_end_regions',
            'afsr_total surface area(mm^2)' : 'afsr_total_surface_area',
            'afsr_trunk volume(mm^3)' : 'afsr_trunk_volume',
            'afsr_volume(mm^3)' : 'afsr_volume',
            'cfpl_ad' : 'cfpl_ad',
            'cfpl_area of end region 1(mm^2)' : 'cfpl_area_of_end_region_1',
            'cfpl_area of end region 2(mm^2)' : 'cfpl_area_of_end_region_2',
            'cfpl_branch volume(mm^3)' : 'cfpl_branch_volume',
            'cfpl_curl' : 'cfpl_curl',
            'cfpl_diameter(mm)' : 'cfpl_diameter',
            'cfpl_dti_fa' : 'cfpl_dti_fa',
            'cfpl_elongation' : 'cfpl_elongation',
            'cfpl_irregularity' : 'cfpl_irregularity',
            'cfpl_irregularity of end region 1' : 'cfpl_irregularity_of_end_region_1',
            'cfpl_irregularity of end region 2' : 'cfpl_irregularity_of_end_region_2',
            'cfpl_iso' : 'cfpl_iso',
            'cfpl_md' : 'cfpl_md',
            'cfpl_mean length(mm)' : 'cfpl_mean_length',
            'cfpl_nrdi02L' : 'cfpl_nrdi02L',
            'cfpl_nrdi04L' : 'cfpl_nrdi04L',
            'cfpl_nrdi06L' : 'cfpl_nrdi06L',
            'cfpl_number of tracts' : 'cfpl_number_of_tracts',
            'cfpl_qa' : 'cfpl_qa',
            'cfpl_radius of end region 1(mm)' : 'cfpl_radius_of_end_region_1',
            'cfpl_radius of end region 2(mm)' : 'cfpl_radius_of_end_region_2',
            'cfpl_rd':'cfpl_rd',
            'cfpl_rdi': 'cfpl_rdi',
            'cfpl_span(mm)' : 'cfpl_span',
            'cfpl_total area of end regions(mm^2)' : 'cfpl_total_area_of_end_regions',
            'cfpl_total radius of end regions(mm)' : 'cfpl_total_radius_of_end_regions',
            'cfpl_total surface area(mm^2)' : 'cfpl_total_surface_area',
            'cfpl_trunk volume(mm^3)' : 'cfpl_trunk_volume',
            'cfpl_volume(mm^3)' : 'cfpl_volume',
            'cfpr_ad': 'cfpr_ad',
            'cfpr_area of end region 1(mm^2)' : 'cfpr_area_of_end_region_1',
            'cfpr_area of end region 2(mm^2)' : 'cfpr_area_of_end_region_2',
            'cfpr_branch volume(mm^3)' : 'cfpr_branch_volume',
            'cfpr_curl' : 'cfpr_curl',
            'cfpr_diameter(mm)' : 'cfpr_diameter',
            'cfpr_dti_fa' : 'cfpr_dti_fa',
            'cfpr_elongation' : 'cfpr_elongation',
            'cfpr_irregularity' : 'cfpr_irregularity',
            'cfpr_irregularity of end region 1' : 'cfpr_irregularity_of_end_region_1',
            'cfpr_irregularity of end region 2' : 'cfpr_irregularity_of_end_region_2',
            'cfpr_iso' : 'cfpr_iso',
            'cfpr_md' : 'cfpr_md',
            'cfpr_mean length(mm)' : 'cfpr_mean_length',
            'cfpr_nrdi02L' : 'cfpr_nrdi02L',
            'cfpr_nrdi04L' : 'cfpr_nrdi04L',
            'cfpr_nrdi06L' : 'cfpr_nrdi06L',
            'cfpr_number of tracts' : 'cfpr_number_of_tracts',
            'cfpr_qa' : 'cfpr_qa',
            'cfpr_radius of end region 1(mm)' : 'cfpr_radius_of_end_region_1',
            'cfpr_radius of end region 2(mm)' : 'cfpr_radius_of_end_region_2',
            'cfpr_rd' : 'cfpr_rd',
            'cfpr_rdi' : 'cfpr_rdi',
            'cfpr_span(mm)' : 'cfpr_span',
            'cfpr_total area of end regions(mm^2)' : 'cfpr_total_area_of_end_regions',
            'cfpr_total radius of end regions(mm)' : 'cfpr_total_radius_of_end_regions',
            'cfpr_total surface area(mm^2)' : 'cfpr_total_surface_area',
            'cfpr_trunk volume(mm^3)' : 'cfpr_trunk_volume',
            'cfpr_volume(mm^3)' : 'cfpr_volume',
            'fatl_ad' : 'fatl_ad',
            'fatl_area of end region 1(mm^2)' : 'fatl_area_of_end_region_1',
            'fatl_area of end region 2(mm^2)' : 'fatl_area_of_end_region_2',
            'fatl_branch volume(mm^3)' : 'fatl_branch_volume',
            'fatl_curl' : 'fatl_curl',
            'fatl_diameter(mm)' : 'fatl_diameter',
            'fatl_dti_fa' : 'fatl_dti_fa',
            'fatl_elongation' : 'fatl_elongation',
            'fatl_irregularity' : 'fatl_irregularity',
            'fatl_irregularity of end region 1' : 'fatl_irregularity_of_end_region_1',
            'fatl_irregularity of end region 2' : 'fatl_irregularity_of_end_region_2',
            'fatl_iso' : 'fatl_iso',
            'fatl_md' : 'fatl_md',
            'fatl_mean length(mm)' : 'fatl_mean_length',
            'fatl_nrdi02L' : 'fatl_nrdi02L',
            'fatl_nrdi04L' : 'fatl_nrdi04L',
            'fatl_nrdi06L' : 'fatl_nrdi06L',
            'fatl_number of tracts' : 'fatl_number_of_tracts',
            'fatl_qa' : 'fatl_qa',
            'fatl_radius of end region 1(mm)' : 'fatl_radius_of_end_region_1',
            'fatl_radius of end region 2(mm)' : 'fatl_radius_of_end_region_2',
            'fatl_rd' : 'fatl_rd',
            'fatl_rdi' : 'fatl_rdi',
            'fatl_span(mm)' : 'fatl_span',
            'fatl_total area of end regions(mm^2)' : 'fatl_total_area_of_end_regions',
            'fatl_total radius of end regions(mm)' : 'fatl_total_radius_of_end_regions',
            'fatl_total surface area(mm^2)' : 'fatl_total_surface_area',
            'fatl_trunk volume(mm^3)' : 'fatl_trunk_volume',
            'fatl_volume(mm^3)' : 'fatl_volume',
            'fatr_ad' : 'fatr_ad',
            'fatr_area of end region 1(mm^2)' : 'fatr_area_of_end_region_1',
            'fatr_area of end region 2(mm^2)' : 'fatr_area_of_end_region_2',
            'fatr_branch volume(mm^3)' : 'fatr_branch_volume',
            'fatr_curl' : 'fatr_curl',
            'fatr_diameter(mm)' : 'fatr_diameter',
            'fatr_dti_fa' : 'fatr_dti_fa',
            'fatr_elongation' : 'fatr_elongation',
            'fatr_irregularity' : 'fatr_irregularity',
            'fatr_irregularity of end region 1' : 'fatr_irregularity_of_end_region_1',
            'fatr_irregularity of end region 2' : 'fatr_irregularity_of_end_region_2',
            'fatr_iso' : 'fatr_iso',
            'fatr_md' : 'fatr_md',
            'fatr_mean length(mm)' : 'fatr_mean_length',
            'fatr_nrdi02L' : 'fatr_nrdi02L',
            'fatr_nrdi04L' : 'fatr_nrdi04L',
            'fatr_nrdi06L' : 'fatr_nrdi06L',
            'fatr_number of tracts' : 'fatr_number_of_tracts',
            'fatr_qa' : 'fatr_qa',
            'fatr_radius of end region 1(mm)' : 'fatr_radius_of_end_region_1',
            'fatr_radius of end region 2(mm)' : 'fatr_radius_of_end_region_2',
            'fatr_rd' : 'fatr_rd',
            'fatr_rdi' : 'fatr_rdi',
            'fatr_span(mm)' : 'fatr_span',
            'fatr_total area of end regions(mm^2)' : 'fatr_total_area_of_end_regions',
            'fatr_total radius of end regions(mm)' : 'fatr_total_radius_of_end_regions',
            'fatr_total surface area(mm^2)' : 'fatr_total_surface_area',
            'fatr_trunk volume(mm^3)' : 'fatr_trunk_volume',
            'fatr_volume(mm^3)' : 'fatr_volume',
            'slfl_ad' : 'slfl_ad',
            'slfl_area of end region 1(mm^2)' : 'slfl_area_of_end_region_1',
            'slfl_area of end region 2(mm^2)' : 'slfl_area_of_end_region_2',
            'slfl_branch volume(mm^3)' : 'slfl_branch_volume',
            'slfl_curl' : 'slfl_curl',
            'slfl_diameter(mm)' : 'slfl_diameter',
            'slfl_dti_fa' : 'slfl_dti_fa',
            'slfl_elongation' : 'slfl_elongation',
            'slfl_irregularity' : 'slfl_irregularity',
            'slfl_irregularity of end region 1' : 'slfl_irregularity_of_end_region_1',
            'slfl_irregularity of end region 2' : 'slfl_irregularity_of_end_region_2',
            'slfl_iso' : 'slfl_iso',
            'slfl_md' : 'slfl_md',
            'slfl_mean length(mm)' : 'slfl_mean_length',
            'slfl_nrdi02L' : 'slfl_nrdi02L',
            'slfl_nrdi04L' : 'slfl_nrdi04L',
            'slfl_nrdi06L' : 'slfl_nrdi06L',
            'slfl_number of tracts' : 'slfl_number_of_tracts',
            'slfl_qa' : 'slfl_qa',
            'slfl_radius of end region 1(mm)' : 'slfl_radius_of_end_region_1',
            'slfl_radius of end region 2(mm)' : 'slfl_radius_of_end_region_2',
            'slfl_rd' : 'slfl_rd',
            'slfl_rdi' : 'slfl_rdi',
            'slfl_span(mm)' : 'slfl_span',
            'slfl_total area of end regions(mm^2)' : 'slfl_total_area_of_end_regions',
            'slfl_total radius of end regions(mm)' : 'slfl_total_radius_of_end_regions',
            'slfl_total surface area(mm^2)' : 'slfl_total_surface_area',
            'slfl_trunk volume(mm^3)' : 'slfl_trunk_volume',
            'slfl_volume(mm^3)' : 'slfl_volume',
            'slfr_ad' : 'slfr_ad',
            'slfr_area of end region 1(mm^2)' : 'slfr_area_of_end_region_1',
            'slfr_area of end region 2(mm^2)' : 'slfr_area_of_end_region_2',
            'slfr_branch volume(mm^3)' : 'slfr_branch_volume',
            'slfr_curl' : 'slfr_curl',
            'slfr_diameter(mm)' : 'slfr_diameter',
            'slfr_dti_fa' : 'slfr_dti_fa',
            'slfr_elongation' : 'slfr_elongation',
            'slfr_irregularity' : 'slfr_irregularity',
            'slfr_irregularity of end region 1' : 'slfr_irregularity_of_end_region_1',
            'slfr_irregularity of end region 2' : 'slfr_irregularity_of_end_region_2',
            'slfr_iso' : 'slfr_iso',
            'slfr_md' : 'slfr_md',
            'slfr_mean length(mm)' : 'slfr_mean_length',
            'slfr_nrdi02L' : 'slfr_nrdi02L',
            'slfr_nrdi04L' : 'slfr_nrdi04L',
            'slfr_nrdi06L' : 'slfr_nrdi06L',
            'slfr_number of tracts' : 'slfr_number_of_tracts',
            'slfr_qa' : 'slfr_qa',
            'slfr_radius of end region 1(mm)' : 'slfr_radius_of_end_region_1',
            'slfr_radius of end region 2(mm)' : 'slfr_radius_of_end_region_2',
            'slfr_rd' : 'slfr_rd',
            'slfr_rdi' : 'slfr_rdi',
            'slfr_span(mm)' : 'slfr_span',
            'slfr_total area of end regions(mm^2)' : 'slfr_total_area_of_end_regions',
            'slfr_total radius of end regions(mm)' : 'slfr_total_radius_of_end_regions',
            'slfr_total surface area(mm^2)' : 'slfr_total_surface_area',
            'slfr_trunk volume(mm^3)' : 'slfr_trunk_volume',
            'slfr_volume(mm^3)' : 'slfr_volume',
            'ufsl_ad' : 'ufsl_ad',
            'ufsl_area of end region 1(mm^2)' : 'ufsl_area_of_end_region_1',
            'ufsl_area of end region 2(mm^2)' : 'ufsl_area_of_end_region_2',
            'ufsl_branch volume(mm^3)' : 'ufsl_branch_volume',
            'ufsl_curl' : 'ufsl_curl',
            'ufsl_diameter(mm)' : 'ufsl_diameter',
            'ufsl_dti_fa' : 'ufsl_dti_fa',
            'ufsl_elongation' : 'ufsl_elongation',
            'ufsl_irregularity' : 'ufsl_irregularity',
            'ufsl_irregularity of end region 1' : 'ufsl_irregularity_of_end_region_1',
            'ufsl_irregularity of end region 2' : 'ufsl_irregularity_of_end_region_2',
            'ufsl_iso' : 'ufsl_iso',
            'ufsl_md' : 'ufsl_md',
            'ufsl_mean length(mm)' : 'ufsl_mean_length',
            'ufsl_nrdi02L' : 'ufsl_nrdi02L',
            'ufsl_nrdi04L' : 'ufsl_nrdi04L',
            'ufsl_nrdi06L' : 'ufsl_nrdi06L',
            'ufsl_number of tracts' : 'ufsl_number_of_tracts',
            'ufsl_qa' : 'ufsl_qa',
            'ufsl_radius of end region 1(mm)' : 'ufsl_radius_of_end_region_1',
            'ufsl_radius of end region 2(mm)' : 'ufsl_radius_of_end_region_2',
            'ufsl_rd' : 'ufsl_rd',
            'ufsl_rdi' : 'ufsl_rdi',
            'ufsl_span(mm)' : 'ufsl_span',
            'ufsl_total area of end regions(mm^2)' : 'ufsl_total_area_of_end_regions',
            'ufsl_total radius of end regions(mm)' : 'ufsl_total_radius_of_end_regions',
            'ufsl_total surface area(mm^2)' : 'ufsl_total_surface_area',
            'ufsl_trunk volume(mm^3)' : 'ufsl_trunk_volume',
            'ufsl_volume(mm^3)' : 'ufsl_volume',
            'ufsr_ad' : 'ufsr_ad',
            'ufsr_area of end region 1(mm^2)' : 'ufsr_area_of_end_region_1',
            'ufsr_area of end region 2(mm^2)' : 'ufsr_area_of_end_region_2',
            'ufsr_branch volume(mm^3)' : 'ufsr_branch_volume',
            'ufsr_curl' : 'ufsr_curl',
            'ufsr_diameter(mm)' : 'ufsr_diameter',
            'ufsr_dti_fa' : 'ufsr_dti_fa',
            'ufsr_elongation' : 'ufsr_elongation',
            'ufsr_irregularity' : 'ufsr_irregularity',
            'ufsr_irregularity of end region 1' : 'ufsr_irregularity_of_end_region_1',
            'ufsr_irregularity of end region 2' : 'ufsr_irregularity_of_end_region_2',
            'ufsr_iso' : 'ufsr_iso',
            'ufsr_md' : 'ufsr_md',
            'ufsr_mean length(mm)' : 'ufsr_mean_length',
            'ufsr_nrdi02L' : 'ufsr_nrdi02L',
            'ufsr_nrdi04L' : 'ufsr_nrdi04L',
            'ufsr_nrdi06L' : 'ufsr_nrdi06L',
            'ufsr_number of tracts' : 'ufsr_number_of_tracts',
            'ufsr_qa' : 'ufsr_qa',
            'ufsr_radius of end region 1(mm)' : 'ufsr_radius_of_end_region_1',
            'ufsr_radius of end region 2(mm)' : 'ufsr_radius_of_end_region_2',
            'ufsr_rd' : 'ufsr_rd',
            'ufsr_rdi' : 'ufsr_rdi',
            'ufsr_span(mm)' : 'ufsr_span',
            'ufsr_total area of end regions(mm^2)' : 'ufsr_total_area_of_end_regions',
            'ufsr_total radius of end regions(mm)' : 'ufsr_total_radius_of_end_regions',
            'ufsr_total surface area(mm^2)' : 'ufsr_total_surface_area',
            'ufsr_trunk volume(mm^3)' : 'ufsr_trunk_volume',
            'ufsr_volume(mm^3)' : 'ufsr_volume'}
    return label

def columnas():
        columnas = [
        'ufsl_branch_volume',
        'slfr_total_area_of_end_regions',
        'slfl_md',
        'afsr_span',
        'cfpr_span',
        'afsl_irregularity_of_end_region_1',
        'cfpr_radius_of_end_region_2',
        'ufsr_radius_of_end_region_2',
        'cfpr_irregularity_of_end_region_1',
        'fatr_irregularity_of_end_region_1',
        'ufsr_irregularity_of_end_region_1',
        'cfpl_ad',
        'fatl_ad',
        'ufsl_ad',
        'afsl_irregularity_of_end_region_2',
        'cfpr_dti_fa',
        'fatr_dti_fa',
        'cfpl_irregularity_of_end_region_2',
        'afsr_dti_fa',
        'ufsr_ad',
        'afsr_radius_of_end_region_2',
        'slfr_radius_of_end_region_2',
        'afsl_trunk_volume',
        'afsr_curl',
        'slfr_mean_length',
        'fatl_volume',
        'fatr_branch_volume',
        'fatr_nrdi02L',
        'cfpl_radius_of_end_region_2',
        'afsl_md',
        'slfr_total_radius_of_end_regions',
        'slfr_irregularity_of_end_region_2',
        'ufsl_diameter',
        'ufsl_irregularity',
        'ufsl_nrdi02L',
        'ufsl_nrdi04L',
        'ufsl_nrdi06L',
        'ufsl_rdi',
        'afsr_irregularity_of_end_region_2',
        'fatr_elongation',
        'ufsr_elongation',
        'cfpl_area_of_end_region_1',
        'fatr_span',
        'ufsr_span',
        'slfl_area_of_end_region_1',
        'cfpr_irregularity_of_end_region_2',
        'fatr_irregularity_of_end_region_2',
        'ufsr_irregularity_of_end_region_2',
        'afsr_elongation',
        'cfpr_elongation',
        'cfpl_trunk_volume',
        'fatl_trunk_volume',
        'ufsl_trunk_volume',
        'slfl_curl',
        'afsl_diameter',
        'afsl_irregularity',
        'afsl_nrdi02L',
        'afsl_nrdi04L',
        'afsl_nrdi06L',
        'afsr_branch_volume',
        'afsr_nrdi04L',
        'afsr_total_radius_of_end_regions',
        'afsr_total_surface_area',
        'cfpl_diameter',
        'cfpl_irregularity',
        'cfpl_total_radius_of_end_regions',
        'cfpl_volume',
        'cfpr_branch_volume',
        'cfpr_nrdi02L',
        'cfpr_nrdi04L',
        'cfpr_qa',
        'cfpr_rdi',
        'cfpr_total_radius_of_end_regions',
        'cfpr_total_surface_area',
        'fatl_diameter',
        'fatl_irregularity',
        'fatl_nrdi02L',
        'fatl_nrdi04L',
        'fatl_nrdi06L',
        'fatl_rdi',
        'fatl_total_radius_of_end_regions',
        'fatr_qa',
        'fatr_rdi',
        'fatr_total_radius_of_end_regions',
        'fatr_total_surface_area',
        'slfr_radius_of_end_region_1',
        'ufsr_dti_fa',
        'slfl_branch_volume',
        'slfl_span',
        'cfpr_curl',
        'fatr_curl']
        return columnas
